const images = {
    "13": require("./images/levels/a.png"),
    "21": require("./images/levels/b.png"),
    "8": require("./images/levels/c.png"),
    "15": require("./images/levels/d.png"),
    "3": require("./images/levels/euro.png"),
    "24": require("./images/levels/f.png"),
    "9": require("./images/levels/g.png"),
    "4": require("./images/levels/h.png"),
    "18": require("./images/levels/i.png"),
    "22": require("./images/levels/j.png"),
    "10": require("./images/levels/k.png"),
    "14": require("./images/levels/l.png"),
    "6": require("./images/levels/m.png"),
    "11": require("./images/levels/n.png"),
    "1": require("./images/levels/ladder.png"),
    "16": require("./images/levels/p.png"),
    "26": require("./images/levels/q.png"),
    "12": require("./images/levels/r.png"),
    "20": require("./images/levels/s.png"),
    "2": require("./images/levels/dollar.png"),
    "5": require("./images/levels/u.png"),
    "7": require("./images/levels/v.png"),
    "23": require("./images/levels/w.png"),
    "25": require("./images/levels/x.png"),
    "19": require("./images/levels/y.png"),
    "17": require("./images/levels/z.png"),
}

export default images;
